apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/
    repoURL: https://github.com/myhailo-rudenko/argocd-app-of-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
