---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argo-cd
spec:
  project: default
  source:
    chart: kibana
    repoURL: https://helm.elastic.co
    targetRevision: 7.17.3
    helm:
      values: |
        elasticsearchHosts: "https://elasticsearch.k8s-c02.ubn24.de"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: 'true'
            cert-manager.io/cluster-issuer: letsencrypt-staging
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
            nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
          hosts:
            - host: kibana.k8s-c02.ubn24.de
              paths:
                - path: /
          tls:
           - secretName: kibana.k8s-c02.ubn24.de-tls
             hosts:
               - kibana.k8s-c02.ubn24.de
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
