---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.0
    helm:
      values: |
        controller:
          service:
            externalTrafficPolicy: Cluster
            externalIPs:
              - 10.10.10.11
              - 10.10.10.12
              - 10.10.10.13
            type: NodePort
          metrics:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
