---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-c02-root
  namespace: argo-cd
spec:
  project: default
  source:
    path: k8s-c02-chart/
    repoURL: https://github.com/myhailo-rudenko/argocd-app-of-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
